### PR TITLE
General update on build and dependencies

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
- Migrate solution to VS2022.
- Fix build issues.
- Update nugets and move .NET to  6.0.
- Bump version to 3.0.
- Brought pipeline definitions up to date.

## Motivation and Context
- Need to have tool available with .NET to  6.0.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Looks good to me

**Comment by networkfusion** [comment]
@josesimoes any reason why this PR fails to finish building? Have I missed something?

**Comment by networkfusion** [comment]
Interesting... I am now getting:

image

**Comment by josesimoes** [comment]
@networkfusion something that need to be fixed in the code... probably some change from VS2017 to VS2022 and new C# and roslyn.

Nothing to worry about as this tool it's doomed to be discontinued. The last release it's working just fine.

**Comment by Ellerbach** [comment]
Still looks good to me ;-)

**Pull request merged**
